server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost/square
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"

my:
  variables:
    url: "http://localhost:8090/user/"