server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost/square
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"

my:
  variables:
    url: "http://localhost:8090/user/"
    admin: "ROLE_ADMIN"
    owner: "ROLE_OWNER"
    employee: "ROLE_EMPLOYEE"
    client: "ROLE_CUSTOMER"
    uri: "http://localhost:8092/messaging/sendMessage/"
    urltrace: "http://localhost:8093/traceability/createTraceability"





